# Generated by ./update.sh - do not update manually!
# Date: 2026-05-30
{
  agentmemory = {
    version = "0.9.24";
    srcHash = "sha256-mTDPTSYS9E7UxFZh0BzvoGh19F7C+PLQv3KM9Q9uSU4=";
    npmDepsHash = "sha256-DuWhb8cz0SL5nPgiTy/CwO3dQYH8n2FLQiRtOE82qgo=";
  };

  iii-engine = {
    version = "0.11.2";
    srcHash = "sha256-nIPEd4i070vutl3ZvzfpT5k3cM09uHRGTDzhzckjUs0=";
  };
}
