# Generated by ./update.sh - do not update manually!
# Date: 2026-05-30
{
  agentmemory = {
    version = "0.9.24";
    srcHash = "sha256-mTDPTSYS9E7UxFZh0BzvoGh19F7C+PLQv3KM9Q9uSU4=";
    npmDepsHash = "sha256-DuWhb8cz0SL5nPgiTy/CwO3dQYH8n2FLQiRtOE82qgo=";
  };

  iii-engine = {
    version = "0.11.2";
    srcHash = "sha256-nIPEd4i070vutl3ZvzfpT5k3cM09uHRGTDzhzckjUs0=";
    initHash = "sha256-OtAc/pSV0dPWZw6Spdbk2vxTA76rM+0Qj3+SUhtuBJw=";
    workerHash = "sha256-+TilB9YyAd8+jsfHeAU7qFCfL1SnaFbi6C6crV7wlM0=";
  };
}
