#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p bash cacert coreutils curl gnutar jq nodejs nix prefetch-npm-deps
# Regenerate sources.nix and package-lock.json from the npm tarball.
# Usage: ./update.sh [agentmemory-version]
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTMEMORY_VERSION="${1:-$(npm view @agentmemory/agentmemory version)}"
TARBALL_URL="https://registry.npmjs.org/@agentmemory/agentmemory/-/agentmemory-${AGENTMEMORY_VERSION}.tgz"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> agentmemory v${AGENTMEMORY_VERSION} update"
echo ""

echo "[1] Downloading agentmemory tarball..."
curl -fsSL "$TARBALL_URL" -o "$WORKDIR/package.tgz"
AGENTMEMORY_SRC_HASH="$(nix hash file --sri --type sha256 "$WORKDIR/package.tgz")"
echo "  source hash (SRI): $AGENTMEMORY_SRC_HASH"

echo "[2] Unpacking tarball..."
tar xzf "$WORKDIR/package.tgz" -C "$WORKDIR"
cd "$WORKDIR/package"

III_ENGINE_VERSION="$(jq -r '.dependencies["iii-sdk"] // empty' package.json)"
if [[ ! "$III_ENGINE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: expected agentmemory to hard-pin iii-sdk, got '$III_ENGINE_VERSION'" >&2
  exit 1
fi
echo "[3] agentmemory pins iii-engine/iii-sdk v${III_ENGINE_VERSION}"

echo "[4] Generating package-lock.json..."
npm install --package-lock-only --ignore-scripts --legacy-peer-deps 2>&1 | tail -1

echo "[5] Copying lockfile..."
cp package-lock.json "$DIR/package-lock.json"
bytes="$(wc -c <"$DIR/package-lock.json")"
printf '  -> %d bytes written\n' "$bytes"

echo "[6] Computing npm dependency hash..."
AGENTMEMORY_NPM_DEPS_HASH="$(prefetch-npm-deps "$DIR/package-lock.json")"
echo "  npmDepsHash: $AGENTMEMORY_NPM_DEPS_HASH"

echo "[7] Downloading iii-engine tarball..."
III_TARGET="x86_64-unknown-linux-gnu"
III_URL="https://github.com/iii-hq/iii/releases/download/iii/v${III_ENGINE_VERSION}/iii-${III_TARGET}.tar.gz"
curl -fsSL "$III_URL" -o "$WORKDIR/iii.tar.gz"
III_SRC_HASH="$(nix hash file --sri --type sha256 "$WORKDIR/iii.tar.gz")"
echo "  iii-engine source hash (SRI): $III_SRC_HASH"

echo "[8] Writing sources.nix..."
cat >"$DIR/sources.nix" <<EOF
# Generated by ./update.sh - do not update manually!
# Date: $(date +%Y-%m-%d)
{
  agentmemory = {
    version = "${AGENTMEMORY_VERSION}";
    srcHash = "${AGENTMEMORY_SRC_HASH}";
    npmDepsHash = "${AGENTMEMORY_NPM_DEPS_HASH}";
  };

  iii-engine = {
    version = "${III_ENGINE_VERSION}";
    srcHash = "${III_SRC_HASH}";
  };
}
EOF

cat <<EOF

==> Updated synced sources
  agentmemory: ${AGENTMEMORY_VERSION}
  iii-engine:  ${III_ENGINE_VERSION}
EOF
