# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  byterover-cli = {
    pname = "byterover-cli";
    version = "3.16.1";
    src = fetchurl {
      url = "https://storage.googleapis.com/brv-releases/channels/stable/brv-linux-x64.tar.gz";
      sha256 = "sha256-V3EVPa6XGqFFJ5FtI486lwtbAKULVHwZw1Tz+oRbRu4=";
    };
  };
  codexbar = {
    pname = "codexbar";
    version = "v0.68.0";
    src = fetchurl {
      url = "https://github.com/steipete/CodeXBar/releases/download/v0.68.0/CodexBarCLI-v0.68.0-linux-x86_64.tar.gz";
      sha256 = "sha256-LZVyiqXrcX0SrApJIMUVN1uTqqWMM2N570612MIO7kk=";
    };
  };
  xberg-cli = {
    pname = "xberg-cli";
    version = "v1.2.9";
    src = fetchurl {
      url = "https://github.com/xberg-io/xberg/releases/download/v1.2.9/xberg-cli-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-S9wor/Xe1vF4puq3rtgbVjKsfk5E0eeEgRht1E1Znn4=";
    };
  };
}
